import { SearchJokes } from '@/types/joke'

export const mockSearchJokes: SearchJokes = {
	total: 50,
	result: [
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-1',
			url: 'https://api.chucknorris.io/jokes/joke-1',
			value: 'Chuck Norris can divide by zero.',
			created_at: '2024-06-18T12:00:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-2',
			url: 'https://api.chucknorris.io/jokes/joke-2',
			value:
				'When Chuck Norris enters a room, he doesn’t turn the lights on. He turns the dark off.',
			created_at: '2024-06-18T12:01:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-3',
			url: 'https://api.chucknorris.io/jokes/joke-3',
			value:
				'Chuck Norris doesn’t read books. He stares them down until he gets the information he wants.',
			created_at: '2024-06-18T12:02:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-4',
			url: 'https://api.chucknorris.io/jokes/joke-4',
			value: 'Time waits for no man. Unless that man is Chuck Norris.',
			created_at: '2024-06-18T12:03:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-5',
			url: 'https://api.chucknorris.io/jokes/joke-5',
			value: 'Chuck Norris can slam a revolving door.',
			created_at: '2024-06-18T12:04:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-6',
			url: 'https://api.chucknorris.io/jokes/joke-6',
			value: 'Chuck Norris can win a game of Connect Four in only three moves.',
			created_at: '2024-06-18T12:05:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-7',
			url: 'https://api.chucknorris.io/jokes/joke-7',
			value:
				'Once a cobra bit Chuck Norris’ leg. After five days of excruciating pain, the cobra died.',
			created_at: '2024-06-18T12:06:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-8',
			url: 'https://api.chucknorris.io/jokes/joke-8',
			value: 'Chuck Norris doesn’t cheat death. He wins fair and square.',
			created_at: '2024-06-18T12:07:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-9',
			url: 'https://api.chucknorris.io/jokes/joke-9',
			value: 'Chuck Norris can hear sign language.',
			created_at: '2024-06-18T12:08:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-10',
			url: 'https://api.chucknorris.io/jokes/joke-10',
			value: 'Chuck Norris can drown a fish.',
			created_at: '2024-06-18T12:09:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-11',
			url: 'https://api.chucknorris.io/jokes/joke-11',
			value: 'Chuck Norris can play the violin with a piano.',
			created_at: '2024-06-18T12:10:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-12',
			url: 'https://api.chucknorris.io/jokes/joke-12',
			value:
				'Chuck Norris once got bitten by a rattlesnake. After three days of pain and agony, the rattlesnake died.',
			created_at: '2024-06-18T12:11:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-13',
			url: 'https://api.chucknorris.io/jokes/joke-13',
			value: 'Chuck Norris makes onions cry.',
			created_at: '2024-06-18T12:12:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-14',
			url: 'https://api.chucknorris.io/jokes/joke-14',
			value: 'Chuck Norris can unscramble an egg.',
			created_at: '2024-06-18T12:13:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-15',
			url: 'https://api.chucknorris.io/jokes/joke-15',
			value: 'Chuck Norris can do a wheelie on a unicycle.',
			created_at: '2024-06-18T12:14:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-16',
			url: 'https://api.chucknorris.io/jokes/joke-16',
			value: 'Chuck Norris counted to infinity. Twice.',
			created_at: '2024-06-18T12:15:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-17',
			url: 'https://api.chucknorris.io/jokes/joke-17',
			value:
				'When Chuck Norris does a pushup, he isn’t lifting himself up, he’s pushing the Earth down.',
			created_at: '2024-06-18T12:16:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-18',
			url: 'https://api.chucknorris.io/jokes/joke-18',
			value: 'Chuck Norris doesn’t wear a watch. He decides what time it is.',
			created_at: '2024-06-18T12:17:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-19',
			url: 'https://api.chucknorris.io/jokes/joke-19',
			value: 'Chuck Norris can light a fire by rubbing two ice-cubes together.',
			created_at: '2024-06-18T12:18:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-20',
			url: 'https://api.chucknorris.io/jokes/joke-20',
			value: 'Chuck Norris can kill two stones with one bird.',
			created_at: '2024-06-18T12:19:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-21',
			url: 'https://api.chucknorris.io/jokes/joke-21',
			value: 'Chuck Norris can speak braille.',
			created_at: '2024-06-18T12:20:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-22',
			url: 'https://api.chucknorris.io/jokes/joke-22',
			value: 'Chuck Norris knows Victoria’s secret.',
			created_at: '2024-06-18T12:21:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-23',
			url: 'https://api.chucknorris.io/jokes/joke-23',
			value: 'Chuck Norris’ tears cure cancer. Too bad he has never cried.',
			created_at: '2024-06-18T12:22:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-24',
			url: 'https://api.chucknorris.io/jokes/joke-24',
			value: 'Chuck Norris can strangle you with a cordless phone.',
			created_at: '2024-06-18T12:23:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-25',
			url: 'https://api.chucknorris.io/jokes/joke-25',
			value: 'Chuck Norris can make a Happy Meal cry.',
			created_at: '2024-06-18T12:24:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-26',
			url: 'https://api.chucknorris.io/jokes/joke-26',
			value: 'Chuck Norris can do a wheelie on a bicycle without wheels.',
			created_at: '2024-06-18T12:25:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-27',
			url: 'https://api.chucknorris.io/jokes/joke-27',
			value:
				'Chuck Norris once kicked a horse in the chin. Its descendants are known today as giraffes.',
			created_at: '2024-06-18T12:26:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-28',
			url: 'https://api.chucknorris.io/jokes/joke-28',
			value:
				'Chuck Norris can pick oranges from an apple tree and make the best lemonade you’ve ever tasted.',
			created_at: '2024-06-18T12:27:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-29',
			url: 'https://api.chucknorris.io/jokes/joke-29',
			value: 'Chuck Norris can unscramble an egg.',
			created_at: '2024-06-18T12:28:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-30',
			url: 'https://api.chucknorris.io/jokes/joke-30',
			value: 'Chuck Norris can divide by zero.',
			created_at: '2024-06-18T12:29:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-31',
			url: 'https://api.chucknorris.io/jokes/joke-31',
			value: 'Chuck Norris can hear sign language.',
			created_at: '2024-06-18T12:30:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-32',
			url: 'https://api.chucknorris.io/jokes/joke-32',
			value: 'Chuck Norris can dribble a bowling ball.',
			created_at: '2024-06-18T12:31:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-33',
			url: 'https://api.chucknorris.io/jokes/joke-33',
			value: 'Chuck Norris can unscramble an egg.',
			created_at: '2024-06-18T12:32:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-34',
			url: 'https://api.chucknorris.io/jokes/joke-34',
			value: 'Chuck Norris can kill your imaginary friends.',
			created_at: '2024-06-18T12:33:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-35',
			url: 'https://api.chucknorris.io/jokes/joke-35',
			value: 'Chuck Norris can win a game of Connect Four in only three moves.',
			created_at: '2024-06-18T12:34:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-36',
			url: 'https://api.chucknorris.io/jokes/joke-36',
			value: 'When Chuck Norris does a pushup, he’s pushing the Earth down.',
			created_at: '2024-06-18T12:35:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-37',
			url: 'https://api.chucknorris.io/jokes/joke-37',
			value: 'Chuck Norris can make onions cry.',
			created_at: '2024-06-18T12:36:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-38',
			url: 'https://api.chucknorris.io/jokes/joke-38',
			value: 'Chuck Norris can strangle you with a cordless phone.',
			created_at: '2024-06-18T12:37:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-39',
			url: 'https://api.chucknorris.io/jokes/joke-39',
			value: 'Chuck Norris can play the violin with a piano.',
			created_at: '2024-06-18T12:38:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-40',
			url: 'https://api.chucknorris.io/jokes/joke-40',
			value: 'Chuck Norris doesn’t cheat death. He wins fair and square.',
			created_at: '2024-06-18T12:39:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-41',
			url: 'https://api.chucknorris.io/jokes/joke-41',
			value:
				'When Chuck Norris enters a room, he doesn’t turn the lights on. He turns the dark off.',
			created_at: '2024-06-18T12:40:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-42',
			url: 'https://api.chucknorris.io/jokes/joke-42',
			value:
				'Chuck Norris doesn’t read books. He stares them down until he gets the information he wants.',
			created_at: '2024-06-18T12:41:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-43',
			url: 'https://api.chucknorris.io/jokes/joke-43',
			value: 'Chuck Norris can dribble a bowling ball.',
			created_at: '2024-06-18T12:42:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-44',
			url: 'https://api.chucknorris.io/jokes/joke-44',
			value:
				'Chuck Norris once kicked a horse in the chin. Its descendants are known today as giraffes.',
			created_at: '2024-06-18T12:43:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-45',
			url: 'https://api.chucknorris.io/jokes/joke-45',
			value: 'Chuck Norris can speak braille.',
			created_at: '2024-06-18T12:44:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-46',
			url: 'https://api.chucknorris.io/jokes/joke-46',
			value: 'Chuck Norris can win a game of Connect Four in only three moves.',
			created_at: '2024-06-18T12:45:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-47',
			url: 'https://api.chucknorris.io/jokes/joke-47',
			value: 'Chuck Norris counted to infinity. Twice.',
			created_at: '2024-06-18T12:46:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-48',
			url: 'https://api.chucknorris.io/jokes/joke-48',
			value: 'Chuck Norris can make a Happy Meal cry.',
			created_at: '2024-06-18T12:47:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-49',
			url: 'https://api.chucknorris.io/jokes/joke-49',
			value: 'Chuck Norris doesn’t cheat death. He wins fair and square.',
			created_at: '2024-06-18T12:48:00Z',
		},
		{
			icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
			id: 'joke-50',
			url: 'https://api.chucknorris.io/jokes/joke-50',
			value: 'Time waits for no man. Unless that man is Chuck Norris.',
			created_at: '2024-06-18T12:49:00Z',
		},
	],
}
