import { GetStaticProps } from 'next'
import { Open_Sans } from 'next/font/google'
import Head from 'next/head'

const open_sans = Open_Sans({ subsets: ['latin'], weight: ['400', '700'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={open_sans.className} />
		</>
	)
}

export const getStaticProps: GetStaticProps = async () => {
	return {
		redirect: {
			destination: '/search',
			permanent: false,
		},
	}
}
